---
- name: Ensure group docker exists
  group:
    name: docker
    state: present
  register: docker_group

- name: Load user based on OS
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    group: docker
  when:
    - docker_group is defined 
    - docker_group.state == "present"